### ISSUE TITLE
How to handle language in eg. Type?

### ISSUE THREAD

**Issue by ivozandhuis** [vangoghworldwide/linkedart#12]
We use linked-art patterns for the language of the title. Does this pattern apply to rdfs:labels as well?

**Comment by vangoghworldwide** [comment]
No. rdfs:label is only intended for human users looking at the data. Do we describe the use rdfs:label in a different way somewhere? Then we should fix that.

**Comment by ivozandhuis** [comment]
You mean we don't handle language at all? KMM provides labels on their data in both Dutch and English.

**Comment by vangoghworldwide** [comment]
See the description of _label (rdfs:label) on https://linked.art/model/base/.

Where does KMM want to use rdfs:label? For concepts? 

I see two scenarios
1. A getty concept is used. In this case an rdfs:label is provided with the purpose as described in linked art.
2. A concept from an interval thesaurus is used. In this case language tags may be provided. Typically skos is used in this case.

**Comment by ivozandhuis** [comment]
```
<crm:E57_Material>
<rdfs:label>graphite pencils</rdfs:label>
<crm:P72_has_language>
<crm:E56_Language rdf:about="http://vocab.getty.edu/aat/300388277"/>
</crm:P72_has_language>
</crm:E57_Material>
```

**Comment by vangoghworldwide** [comment]
This states that the language of the material is English. As far as I have seen the language pattern is only used for Names and Linguistic Objects. 

Is it correct that there are no AAT concepts available for this material?

**Comment by vangoghworldwide** [comment]
When you want to model concepts from an internal thesaurus, just use skos. With a prefLabel and language tags. As you also did for RKD.

Afterall the getty AAT is also in skos. 

When we really need textual descriptions for materials we can grab the statement pattern:
https://linked.art/model/object/physical/#materials-statement

But I prefer to stay away from this. It will be horrible for a web developer to deal with this.

**Comment by ivozandhuis** [comment]
How about this:
case 1: linked to AAT, but with additional altLabels
```
<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#" xmlns:crm="http://www.cidoc-crm.org/cidoc-crm/" xmlns:skos="http://www.w3.org/2004/02/skos/core#">
  <crm:E22_Human-Made_Object rdf:about="http://vangoghmuseum.nl/data/artwork/s0416M1990">
    <crm:P45_consists_of>
      <crm:E57_Material rdf:about="http://vocab.getty.edu/aat/300015050">
        <rdfs:label>oil paint</rdfs:label>
        <skos:altLabel xml:lang="en">oil paint</skos:altLabel>
        <skos:altLabel xml:lang="nl">olieverf</skos:altLabel>
      </crm:E57_Material>
    </crm:P45_consists_of>
  </crm:E22_Human-Made_Object>
</rdf:RDF>
```
* it complies to linked art wih the rdfs:label (without language)
* it adds extra labels that can be used in the context of another language

case 2: linked to own thesaurus, with exactMatch to AAT
```
<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#" xmlns:crm="http://www.cidoc-crm.org/cidoc-crm/" xmlns:skos="http://www.w3.org/2004/02/skos/core#">
  <crm:E22_Human-Made_Object rdf:about="http://vangoghmuseum.nl/data/artwork/s0416M1990">
    <crm:P45_consists_of>
      <crm:E57_Material rdf:about="http://vangoghmuseum.nl/data/thesaurus/29309481203948">
      	<rdf:type rdf:resource="http://www.w3.org/2004/02/skos/core#Concept"/>
        <rdfs:label>oil paint</rdfs:label>
        <skos:prefLabel xml:lang="en">oil paint</skos:prefLabel>
        <skos:altLabel xml:lang="nl">olieverf</skos:altLabel>
        <skos:exactMatch rdf:resource="http://vocab.getty.edu/aat/300015050"/>
      </crm:E57_Material>
    </crm:P45_consists_of>
  </crm:E22_Human-Made_Object>
</rdf:RDF>
```
* (it differs from case 1 in that I introduce a new skos:Concept with its own uri)

**Comment by vangoghworldwide** [comment]
Both cases are "allowed". The pref and alt labels are not necessary. VGW platform has loaded the getty vocabularies. It already contains the labels in multiple languages. At the other hand they are not forbidden either :)

The only case you need to provide skos labels is when an "internal" concept is used and there is no link to a getty concept. 

Thanks for bringing this up. I was not aware this was unclear. I will try to explain it in the documentation.

**Comment by ivozandhuis** [comment]
Well, creating the examples, helped me to understand. We could add the second case as an example in the documentation. I'll create an RDF/XML.

**Comment by ivozandhuis** [comment]
Done. See: skos.rdf.xml or skos.ttl. Do you agree? Could you create a jsonld version?
