### ISSUE TITLE
Broken link to de la Faille open data

### ISSUE THREAD

**Issue by IllyaMoskvin** [vangoghworldwide/linkedart#37]
In the introduction of the README, there is a section talking about Jacob Baart de la Faille:

https://github.com/vangoghworldwide/linkedart/blob/f7603efb72a8a8ce41812bb3431a4eb6f8238391/README.md?plain=1#L4

...which links to here:

https://github.com/vangoghworldwide/delafaille

This link is currently broken.

**Comment by michielhildebrand** [comment]
Thanks. The data is now automatically shared through the linked data service. https://data.spinque.com/ld/data/vangoghworldwide/de_la_faille_1970/

**Comment by IllyaMoskvin** [comment]
Thanks. I have one more, possibly-related follow-up question.

I'm new to linked data, so I'm looking through the n-triples file to get a better understanding of the data.

For example, I'm pretty sure that the Fnumber for [The Bedroom](https://www.artic.edu/artworks/28560/the-bedroom) stored at our institution is F484. So I'm skimming through the data to see what information you already have on it, and I see this line:

```
<https://vangoghworldwide.org/data/artwork/F484> <https://vangoghworldwide.org/data/inDataset> <https://vangoghworldwide.org/data/dataset/delafaille>.
```

In this case, https://vangoghworldwide.org/data/dataset/delafaille also leads to a 404 page.

Is that URI supposed to point at a location with some meaningful data, or is it just an arbitrary identifier?

**Edit:** Fixed Fnumber from F510 to F484. I think F510 came from a 1938 edition of the catalog.

**Comment by michielhildebrand** [comment]
Fair question. In 5* (5 star) linked data this uri should resolve. This can be done with a redirect to https://data.spinque.com/ld/data/vangoghworldwide/de_la_faille_1970/. Van Gogh Worldwide however does not do 5* linked data (yet). So most uris do not resolve. Uris used for artworks from most data providing institutions also do not resolve. These institutions provide linked data themselves, but in the form of a dataset dump in RDF.
