### ISSUE TITLE
Dimension values must be numbers

### ISSUE THREAD

**Issue by IllyaMoskvin** [vangoghworldwide/linkedart#38]
Looking at this example:

https://github.com/vangoghworldwide/linkedart#dimensions

The values are given as strings (`"51.9"` and `"36.4"`).

However, checking the Linked Art Schema docs:

https://linked.art/api/1.0/schema_docs/object/

It looks like `value` is defined as `Type:number`.

Do you care whether we supply value as string or number in the JSON?

**Comment by michielhildebrand** [comment]
At the moment we allow string and number. We don't compute anything with dimensions (yet). I agree with you that the example in the documentation should use number, just in case we want to compute with dimensions in the future.
