### ISSUE TITLE
Formaly attributed to Van Gogh

### ISSUE THREAD

**Issue by ivozandhuis** [vangoghworldwide/linkedart#5]
I noticed on the website some works were no longer attributed to Van Gogh. What pattern is used?

**Comment by vangoghworldwide** [comment]
The creator section is extended with a description of the pattern used for "former attribution" https://github.com/vangoghworldwide/linkedart#creator

**Comment by ivozandhuis** [comment]
What thing should be typed as such? Is the Production-type replaced with this new "former attribution" type?

**Comment by vangoghworldwide** [comment]
I added a description of the previous attribution pattern used in Linked Art. I propose we switch to this.

**Comment by vangoghworldwide** [comment]
@ivozandhuis can you make the corresponding RDF/XML example?

**Comment by ivozandhuis** [comment]
Shouldn't the uri for the assignment be numbered? eg http://vangoghmuseum.nl/data/artwork_production/s0076V1962/assignment/1. In theory there could be more assignments, right?

**Comment by vangoghworldwide** [comment]
Yes. I added it.
